# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='AuthorFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.IntegerField(choices=[(1, 'Coma'), (2, 'Semicolon'), (3, 'Quotatio'), (4, 'Exclamatio'), (5, 'Hyphen'), (6, 'And'), (7, 'But'), (8, 'However'), (9, 'If'), (10, 'That'), (11, 'More'), (12, 'Must'), (13, 'Might'), (14, 'This'), (15, 'Very'), (16, 'Mean Word Length'), (17, 'Mean Sentence Length'), (18, 'Standard deviation of Sentence Length')])),
                ('value', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'author_features',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorship.Author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='FeaturesCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.IntegerField(choices=[(1, 'Coma'), (2, 'Semicolon'), (3, 'Quotatio'), (4, 'Exclamatio'), (5, 'Hyphen'), (6, 'And'), (7, 'But'), (8, 'However'), (9, 'If'), (10, 'That'), (11, 'More'), (12, 'Must'), (13, 'Might'), (14, 'This'), (15, 'Very'), (16, 'Mean Word Length'), (17, 'Mean Sentence Length'), (18, 'Standard deviation of Sentence Length')])),
                ('values', models.CharField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorship.Book')),
            ],
            options={
                'db_table': 'feature_counts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('author', 'name')]),
        ),
    ]
