version: '2'

services:
  percona:
    image: percona:5.6
    volumes:
      - ./compose/percona/datadir:/var/lib/mysql
      - ./compose/percona/logs:/home/logs
      - ./compose/percona/tmp:/tmp
#      - ./compose/percona/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=q1w2e3r4
    ports:
      - "3306:3306"